### PR TITLE
Implemented faster hist filling with cython

### PR DESCRIPTION
**Pull request by guitargeek**
This is doing the histogram creation step about 7 times faster. The small price to pay is that the code now has to be compiled with a "make".

### CODE REVIEW

**Comment by michelif** [comment]
Hi Jonas,
I tested this. If I get this pull request into master and I try to run the step --createHists it doesn't work. 
If I run python tnpEGM_fitter.py etc/config/settings_ele.py --flag passingLoose94X  --createHists
I get the following error:
Error in <TFile::TFile>: file name is not specified
Error in <TTreeFormula::Compile>:  Bad numerical expression : "passingLoose94X"

and then it stay stuck forever. While without this pull requests it works smoothly (I arrived till the end on a small file).  Can you please try to start from the master, add this pull request and try to fix? (maybe something is not committed/updated).
thanks

**Comment by guitargeek** [comment]
Hi, thanks for the feedback! I'll do so and let you know once its fixed.

**Comment by guitargeek** [comment]
Hi, I just merged it with lsoffi/master on my machine and everything works fine. Maybe you just used the wrong config file? To me it seems you just use an outdated config file which is missing the passingLoose94X flag.

**Comment by michelif** [comment]
Hi, but you merged directly on the area from where you did the pull request or start from a clean area?
I did like this:
-start from a clean area
- run in the master all the commands upto createHists step and check that it works
- merge master into your pull request
-run the steps upto:
 python tnpEGM_fitter.py etc/config/settings_ele.py --flag passingLoose94X --createHists
at this step i see the error. Can you try this and send me the exact commands to reproduce?
thanks

**Comment by guitargeek** [comment]
This is what I do, mimicking how the pull request would be:

* git clone -b master git@github.com:lsoffi/egm_tnp_analysis.git
* cd egm_tnp_analysis
* git remote add jonas git@github.com:guitargeek/egm_tnp_analysis.git
* git fetch jonas
* git merge jonas/histUtils_cython
* make
* _cp ~/TnP/egm_tnp_analysis/etc/config/settings_ele.py etc/config/settings_ele.py_
* _cp ~/TnP/egm_tnp_analysis/etc/inputs/tnpSampleDef.py etc/inputs/tnpSampleDef.py_
* python tnpEGM_fitter.py etc/config/settings_ele.py --flag passingLoose94X --createBins
* python tnpEGM_fitter.py etc/config/settings_ele.py --flag passingLoose94X --createHists

Note that I had to copy some etc files from somewhere else, because I'm not on lxplus and I can't run the master with the default input files. So as we did everything similar, apart from not being on lxplus and the config files, the problem must either be the config or the environment.

Which ROOT version are you using? My code relies on a feature which has only been introduced with ROOT 6.10 (almost a year old so I thought it's fair enough). With inferior versions, it might segfault. So if you are experienced with lxplus, maybe you should also change the etc/scripts/setup.sh in a way that a more recent ROOT version is sourced. It is a bit inconsistent to ask for ROOT 6.10+ and then the framework itself doesn't follow that.

**Comment by michelif** [comment]
Hi Jonas,
ok, now I understand. I have created PR #3 to include these changes and also updating some instructions to have it working on lxplus (since it is what people using TnP code generally do)
Can you please test the instruction there? If everything works we will merge that PR and close this.

This improvement is kick ass so I want to keep it, by the way I want to have clear instructions for lxplus and also the possibility for "old" user (aka people using 8_0_X which doesn't have root 6.10) to still run the analysis. 

thanks,
francesco

**Comment by michelif** [comment]
@lsoffi please close this PR without merging. superseeded by #3

**Pull request merged**
